# Generated by Django 6.0.5 on 2026-06-08 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castName', models.CharField(max_length=100)),
                ('isDirector', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreographerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicianName', models.CharField(max_length=100)),
                ('isMusicProducer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductionHouseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('dateOfRelease', models.DateField(default=datetime.date.today)),
                ('allCast', models.ManyToManyField(to='main.cast')),
                ('movieChoreographer', models.ManyToManyField(to='main.choreographer')),
                ('movieGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviegenre')),
                ('movieMusic', models.ManyToManyField(to='main.musicworker')),
                ('movieProducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productionhouse')),
            ],
        ),
    ]
