# Generated by Django 6.0.6 on 2026-06-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='castPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='choreographer',
            name='choreographerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieBanner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieSmallImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='musicworker',
            name='musicianImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='productionHouseLogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
