# Generated by Django 6.0.6 on 2026-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cast_castphoto_choreographer_choreographerimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='castPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='casts/'),
        ),
        migrations.AlterField(
            model_name='choreographer',
            name='choreographerImage',
            field=models.ImageField(blank=True, null=True, upload_to='choreographers/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieBanner',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieSmallImage',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='musicworker',
            name='musicianImage',
            field=models.ImageField(blank=True, null=True, upload_to='musicians/'),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='productionHouseLogo',
            field=models.ImageField(blank=True, null=True, upload_to='productionHouses/'),
        ),
    ]
