# Generated by Django 6.0.6 on 2026-06-09 06:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cast_castphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTopic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateOfContact', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacttopic')),
            ],
        ),
    ]
