# Generated by Django 6.0.6 on 2026-06-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contacttopic_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
