# Generated by Django 6.0.6 on 2026-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_contactus_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieGenre',
        ),
        migrations.AddField(
            model_name='movie',
            name='movieGenre',
            field=models.ManyToManyField(to='main.moviegenre'),
        ),
    ]
