# Generated by Django 6.0.6 on 2026-06-09 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_movie_moviegenre_movie_moviegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieNameSlug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
